books:
  ars-magica-5th-edition-standard-core-rulebook:
    heading_style: toc_or_h1
    chapter_prefix: chapter
  realms-of-power-magic:
    heading_style: toc_or_h1
    chapter_prefix: chapter
  realms-of-power-faerie:
    heading_style: toc_or_h1
    chapter_prefix: chapter
