books:
  ars-magica-5th-edition-standard-core-rulebook:
    heading_style: toc_or_h1
    chapter_prefix: chapter
  lion-and-the-lily-the-norman-tribunal:
    heading_style: toc_or_h1
    chapter_prefix: chapter
  hedge-magic-revised-edition:
    heading_style: toc_or_h1
    chapter_prefix: chapter
